config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :companies, only: %w(index new create)

  constraints(-> (request) { request.subdomain.to_s.match(Company::SUBDOMAIN_REGEXP) }) do
    devise_for :users, controllers: { registrations: "users/registrations" }

    scope module: :companies do
      match "/", to: "posts#index", via: :get
      resource :settings, only: %i(show update)
      resources :users, only: :index
      resources :posts do
        resources :comments, only: %i(index create update destroy), module: :posts
        resource :rating, only: :update, module: :posts, controller: :rating
      end
    end
  end

  root to: "companies#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Authorization

  protect_from_forgery with: :exception

  responders :flash
  respond_to :html

  def after_sign_in_path_for(resource)
    resource.is_a?(AdminUser) ? admin_root_path : root_url(resource.subdomain)
  end

  def signed_in_root_path(resource)
    root_url(resource.subdomain)
  end

  def serialize(resource, options = {})
    ActiveModelSerializers::SerializableResource.new(resource, options)
  end
end

app/views/application/_navigation_main.html.slim
.top-bar-left
  ul.menu
    = link_to "Companies", root_url(subdomain: nil)
    = active_link_to "Blog", root_path,
      active: :exclusive, wrap_tag: :li
    - if user_signed_in?
      = active_link_to "Users", users_path,
        active: :exclusive, wrap_tag: :li

app/views/application/_navigation_user.html.slim
ul.top-bar-right.menu.dropdown(data-dropdown-menu)
  - if user_signed_in?
    li
      a = current_user.full_name
      ul.menu
        li = link_to "Edit profile", edit_user_registration_path
        li = link_to "Create post", new_post_path
        - if policy(current_company).manage?
          li = link_to "Company Setting", settings_path
        li = link_to "Sign out", destroy_user_session_path
  - else
    = active_link_to "Sign in", new_user_session_path, active: :exclusive, wrap_tag: :li
    = active_link_to "Sign up", new_user_registration_path, active: :exclusive, wrap_tag: :li